name: "Deploy Helm to AKS"
description: "Deploys a helm chart to AKS"

inputs:
  azure_client_id:
    description: "Client Id of the Service Principal"
    required: true
  azure_tenant_id:
    description: "Tenant Id of the Service Principal"
    required: true
  azure_subscription_id:
    description: "Subscription Id of the Azure account"
    required: true
  cluster_name:
    description: "Name of AKS cluster"
    required: true
  resource_group:
    description: "Resource group of AKS cluster"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  chart_root:
    description: "Root folder of chart"
    required: true
  namespace:
    description: "Namespace to deploy to"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true

runs:
  using: "composite"
  steps:
  - uses: azure/login@v1
    with:
      client-id: ${{ inputs.azure_client_id }}
      tenant-id: ${{ inputs.azure_tenant_id }}
      subscription-id: ${{ inputs.azure_subscription_id }}

  - uses: azure/aks-set-context@v3
    name: Set AKS context
    with:
      cluster-name: ${{ inputs.cluster_name }}
      resource-group: ${{ inputs.resource_group }}
  
  - name: Set branch name as env variable
    shell: bash
    run: |
      currentbranch=$(echo ${GITHUB_REF##*/})
      echo "running on $currentbranch"
      echo "BRANCH=$currentbranch" >> $GITHUB_ENV
  
  - name: Deploy Chart
    shell: bash
    run: |
      chmod +x deploy-all.sh 
      ./deploy-all.sh --dns aks --aks-name ${{ inputs.cluster_name }} -u ${{ inputs.registry_username }} -p ${{ inputs.registry_password }} --aks-rg ${{ inputs.resource_group }} -r ${{ inputs.registry_host }} -t $TAG --namespace ${{ inputs.namespace }}

    env:
      TAG: ${{ env.BRANCH }}
    working-directory: ${{ inputs.chart_root }}